django/0401/code/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

django/0401/code/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

django/0401/code/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

django/0401/code/crud/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'articles:index' %}">Articles</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

      {% if request.user.is_authenticated %}
            <div class="navbar-nav ms-auto">
              <a class="nav-link active me-3 fs-5" href="{% url 'accounts:profile' request.user.username %}">💗 Hello, <b>{{ request.user }}</b> 💗</a>
              <a class="nav-link mt-1" href="{% url 'accounts:profile' request.user.username %}">내 프로필</a>
              <a class="nav-link mt-1" href="{% url 'accounts:update' %}">회원정보수정</a>
            </div>
            <div class="navbar-nav ms-auto">
              <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-secondary btn-sm mt-1 me-2" value="Logout">
              </form>
              <form action="{% url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-danger btn-sm mt-1" value="탈퇴">
              </form>
            </div>

      {% else %}
        <div class="navbar-nav ms-auto">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          <a class="nav-link"  href="{% url 'accounts:signup' %}">Signup</a>
        </div>
      {% endif %}
      
    </div>
  </div>
</nav>

django/0401/code/crud/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/{개인키}.js" crossorigin="anonymous"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  {% include '_nav.html' %}
  <div class="container mt-4">
    {% block content %}
    {% endblock %}
  </div>
  {% bootstrap_javascript %}
</body>
</html>