django/0401/code/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

django/0401/code/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

django/0401/code/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

django/0401/code/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

django/0401/code/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

django/0401/code/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

django/0401/code/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm, 
    UserCreationForm, 
    PasswordChangeForm,
)
from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST  # DB에 저장 용도 & url로 팔로우 팔로잉 막으려고
def follow(request, user_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    # 내가 팔로잉 할 사람 -> 인스턴스 갖고온 유저
    you = get_object_or_404(get_user_model(), pk=user_pk)
    # 나 -> 요청한 유저
    me = request.user

    if you != me:
        if you.followers.filter(pk=me.pk).exists():
            you.followers.remove(me)
        else:
            you.followers.add(me)
    return redirect('accounts:profile', you.username)

django/0401/code/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

{% if request.resolver_match.url_name == 'login' %}
  <h1>LOGIN</h1>
{% elif request.resolver_match.url_name == 'signup' %}
  <h1>SIGN UP</h1>
{% elif request.resolver_match.url_name == 'update' %}
  <h1>UPDATE</h1>
{% elif request.resolver_match.url_name == 'change_password' %}
  <h1>Change Password</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">
</form>
{% endblock %}

django/0401/code/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load gravatar %}

{% block content %}
<div class="d-flex mb-3">
  <img src="https://s.gravatar.com/avatar/{{ request.user.email|gravatar_url }}?s=80&d=monsterid" alt="gravatar">
  <div class="fs-1 ms-4 d-flex align-items-center">{{ person.username }}님의 프로필</div>
</div>

{% with followings=person.followings.all followers=person.followers.all %}
<div>
  <p>팔로잉 : {{ followings|length }}  |  팔로워 : {{ followers|length }}</p>
  <div>
    <li>팔로잉 : </il>
    {% for following in followings %}
      {{ following }}
    {% endfor %}
    <li>팔로워 : </il>
    {% for follower in followers %}
      {{ follower }}
    {% endfor %}
  </div>
    {% if request.user != person %}
    <div>
      <form action="{% url 'accounts:follow' person.pk%}" method="POST">
        {% csrf_token %}
        {% if request.user in followers %}
          <button>언팔로우</button>
        {% else %}
          <button>팔로우</button>
        {% endif %}
      </form>
    </div>
    {% endif %}
</div>
{% endwith %}
<hr>

<h3>{{ person.username }}'s 게시글</h3>
{% for article in person.article_set.all %}
  <p>{{ article.title }}</p>
{% endfor %}
<hr>

<h3>{{ person.username }}'s 댓글</h3>
{% for comment in person.comment_set.all %}
  <p>{{ comment.content }}</p>
{% endfor %}
<hr>

<h3>{{ person.username }}'s LIKES</h3>
<p>({{ person.like_articles.all|length }})</p>
<hr>

<a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}